### Ejercicio 1.6 - Permutaciones - Felipe González

Una función recursiva que genera e imprime todas las permutaciones de un arreglo se puede plantear
de la siguiente manera:

~~~python
def permutaciones(x,ini,fin):
~~~
   genera las permutaciones del arreglo x desde el elemento
   con índice ini hasta el elemento con índice fin  
   
- Si $ini$ es igual a $fin$ implica que se pide la permutación de un solo elemento, y en ese momento se imprime
  todo el contenido del arreglo
- De lo contrario, para todos los elementos $x[i]$ con $i$ desde $ini$ hasta $fin$ ($fin$ incluido) se hace lo siguiente:

   - Se intercambia el valor del i-ésimo elemento con el inicial
   - Se llama recursivamente a la función permutaciones con el índice del primer elemento incrementado: permutaciones(x, ini+1, fin)
   - Se vuelven a restaurar los valores del elemento inicial con el i-ésimo

Implemente la función "permutaciones" que imprima todas las permutaciones de un arreglo de entrada. Probar su función con arreglos de tamaño 1, 3 y 5.

In [147]:
def permutaciones(x, inicio, fin):
    if inicio == fin:
        print(x)
    else:
        for i in range(inicio, fin):
            x[i], x[inicio] = x[inicio], x[i]
            permutaciones(x, inicio + 1, fin)
            x[i], x[inicio] = x[inicio], x[i]
        

In [148]:
import numpy as np
# Pruebas

one_arr = np.array([69])
three_arr = np.array([223, -69, 42069])
five_arr = np.array([2269, 55454, -1313, -2569, 4277])

all_arrs = [one_arr, three_arr, five_arr]

for arr in all_arrs:
    print(f'Arreglo original: {arr}')
    permutaciones(arr, 0, len(arr))

Arreglo original: [69]
[69]
Arreglo original: [  223   -69 42069]
[  223   -69 42069]
[  223 42069   -69]
[  -69   223 42069]
[  -69 42069   223]
[42069   -69   223]
[42069   223   -69]
Arreglo original: [ 2269 55454 -1313 -2569  4277]
[ 2269 55454 -1313 -2569  4277]
[ 2269 55454 -1313  4277 -2569]
[ 2269 55454 -2569 -1313  4277]
[ 2269 55454 -2569  4277 -1313]
[ 2269 55454  4277 -2569 -1313]
[ 2269 55454  4277 -1313 -2569]
[ 2269 -1313 55454 -2569  4277]
[ 2269 -1313 55454  4277 -2569]
[ 2269 -1313 -2569 55454  4277]
[ 2269 -1313 -2569  4277 55454]
[ 2269 -1313  4277 -2569 55454]
[ 2269 -1313  4277 55454 -2569]
[ 2269 -2569 -1313 55454  4277]
[ 2269 -2569 -1313  4277 55454]
[ 2269 -2569 55454 -1313  4277]
[ 2269 -2569 55454  4277 -1313]
[ 2269 -2569  4277 55454 -1313]
[ 2269 -2569  4277 -1313 55454]
[ 2269  4277 -1313 -2569 55454]
[ 2269  4277 -1313 55454 -2569]
[ 2269  4277 -2569 -1313 55454]
[ 2269  4277 -2569 55454 -1313]
[ 2269  4277 55454 -2569 -1313]
[ 2269  4277 55454 -1313 -25