### Ejercicio 1.4

Suponga que se tiene una matriz $A$ tal que los elementos de cada fila están ordenados ascendentemente, y de la misma manera, los elementos de cada columna también están en orden ascendente. Por ejemplo:

In [1]:
import numpy as np

A = np.array([[10,17,25,36,50,82],
           [15,19,28,45,63,87],
           [21,30,42,56,77,91],
           [27,35,74,84,90,95],
           [40,62,81,86,93,98]])
print(A)
print(A[4,0])

[[10 17 25 36 50 82]
 [15 19 28 45 63 87]
 [21 30 42 56 77 91]
 [27 35 74 84 90 95]
 [40 62 81 86 93 98]]
40


Para simplificar, vamos a suponer que no hay elementos repetidos en la matriz.

Se desea escribir una función que, dado un número $x$, lo busque dentro de la matriz $A$. Si lo encuentra, debe retornar una tupla $(i,j)$ tal que $A[i,j]=x$. Si no lo encuentra debe retornar `None`.

Si la matriz es de $m\times n$, se podría hacer una búsqueda secuencial, la cual en el peor caso demoraría un tiempo proporcional a $m n$. El objetivo de este ejercicio es desarrollar un algoritmo más eficiente, que haga la búsqueda en un tiempo proporcional a $m+n$.

La idea es comenzar comparando $x$ contra el elemento de la esquina inferior izquierda de la matriz, es decir, $A[m-1,0]$. Si $x$ es igual a ese elemento, el algoritmo termina exitosamente. Si no, vemos si $x$ es mayor o menor que él, y dependiendo de eso, podemos ya sea descartar esa fila o esa columna. El proceso se repite con la parte restante de la matriz.

De esta manera, al comenzar una nueva iteración, el invariante sería que la parte de la matriz en donde todavía podría encontrarse $x$ son las filas de la $0$ hasta la $i$ y las columnas desde la $j$ hasta la $n-1$, como ilustra la siguiente figura:

![invariante-matriz](https://github.com/ivansipiran/AED-Apuntes/blob/main/recursos/invariante-matriz.png?raw=1)

La parte de color gris son las filas y columnas que ya han sido descartadas.

Escriba aquí su función y ejecute las pruebas que se indican a continuación:

In [2]:
# Busca x en la matriz A
def busca(x,A):
    m, n = np.shape(A)
    i, j = ((m-1), 0) 
    while i > -1 and j < n:
        if x == A[i, j]:
            return (i, j)
        elif x > A[i, j]:
            j += 1
        elif x < A[i, j]:
            i -= 1
    
        

In [3]:
print(busca(28,A)) # Debe imprimir (1,2)

(1, 2)


In [4]:
print(busca(82,A)) # Debe imprimir (0,5)

(0, 5)


In [5]:
print(busca(33,A)) # Debe imprimir None

None
