# CC3001 Primavera 2024 Tarea 2 Felipe González Poblete

## Shellsort

### Profesores
Sección 1 Patricio Poblete / Nelson Baloian


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos un arreglo "$d$-ordenado" (donde $d$ es un entero mayor o igual a 1) como un arreglo en que cada elemento está ordenado respecto de sus vecinos que están a $d$ casilleros de distancia. Por ejemplo, en el siguiente diagrama se muestran un arreglo antes y después de ser "3-ordenado", destacando en distintos colores las subsecuencias que se forman al considerar elementos que están a distancia 3:

Antes:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Después:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Noten que el caso particular de un arreglo "1-ordenado" (caso $d=1$) sería lo mismo que un arreglo ordenado.

El algoritmo Shellsort consiste en hacer una secuencia de pasadas $d$-ordenando el arreglo, cada vez con un valor diferente de $d$, siendo la última siempre con $d=1$.

Para hacer una pasada de Shellsort elegimos un valor de $d$ y luego aplicamos una versión modificada de ordenación por inserción. La modificación consiste en que la función ``insertar(a,k)`` compara con el elemento $d$ casilleros más atrás, en lugar de hacerlo con el que está uno más atrás.

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_i,d_{i-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [177]:
import numpy as np
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        insertar(a,k)

def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-1]:
        a[j]=a[j-1]
        j-=1
    a[j]=b
    

A = np.array([46,35,95,21,82,70,72,56,64,50])    
print(A)
(insertar(A,3))
print(A)

[46 35 95 21 82 70 72 56 64 50]
[21 46 35 95 82 70 72 56 64 50]


Probemos esto para asegurarnos que funcione bien:

In [178]:
def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print(f"Arreglo {d}-ordenado OK.")

A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar una $d$-ordenación

Modifique el código anterior para que $d$-ordene el arreglo, para un valor de $d$ dado. Para esto, escriba el código de la función ``d_insertar`` en el espacio provisto:

In [179]:
# def d_ordena_insercion(a,d):
#     """d-Ordena el arreglo a por inserción"""
#     n=len(a)
#     for k in range(0, n):
#         d_insertar(a,k,d)


    
# def d_insertar(a,k,d):
#     """
#     Inserta a[k] entre los elementos anteriores a distancia d
#     preservando el orden ascendente (versión 2)
#     """
#     # escriba aquí el código modificado de la función insertar
#     # para que haga una d-inserción en lugar de una inserción
#     b = a[k] # b almacena transitoriamente al elemento a[k]
#     j = k # señala la posición del lugar "vacío"
#     while j >= d and b < a[j-d]:
#         a[j]=a[j-d]
#         j -= d
    
#     a[j] = b
        

In [180]:
def d_ordena_insercion(a,d):
    """d-Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0, n):
        d_insertar(a,k,d)


    
def d_insertar(a,k,d):
    """
    Inserta a[k] entre los elementos anteriores a distancia d
    preservando el orden ascendente (versión 2)
    """
    # escriba aquí el código modificado de la función insertar
    # para que haga una d-inserción en lugar de una inserción
    b = a[k] # b almacena transitoriamente al elemento a[k]
    j = k # señala la posición del lugar "vacío"
    while j >= d and b < a[j-d]:
        a[j]=a[j-d]
        j -= d
    
    a[j] = b
        

Pruebe aquí que su algoritmo $3$-ordena correctamente:

In [181]:
A = np.array([46, 35, 95, 21, 82, 70, 72, 56, 64, 50])
print(A)
d = 3
d_ordena_insercion(A, d)
print(A)
verifica_d_ordenado(A, d)

[46 35 95 21 82 70 72 56 64 50]
[21 35 64 46 56 70 50 82 95 72]
Arreglo 3-ordenado OK.


## 2) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_i=2^i+1$ para $i\ge 1$, y terminando con un $1$. Esto es: $\ldots, 65, 33, 17, 9, 5, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$. Su programa debe partir con el índice $i$ más grande tal que $d_i<n$.

In [182]:
def Shellsort(a):
    """Ordena a usando Shell Sort, con la secuencia de valores …,65,33,17,9,5,3,1"""
    # Se utiliza comprensión de listas para obtener la secuencia requerida
    # 
    seq_d = [(2 ** i + 1 if i != 0 else 1) for i in range(len(a), -1, -1)]
    print(len(seq_d))
    for d in seq_d:
        d_ordena_insercion(a,d)    
    # Escriba aquí el código para invocar d_ordena_insercion reiteradamente
    # con la secuencia de valores indicada

Pruebe aquí su algoritmo de la manera siguiente:

In [183]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
print(A)
Shellsort(A)
print(A)
verifica_d_ordenado(A,1)

[46 35 95 21 82 70 72 56 64 50]
11
[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

In [184]:
R = np.random.rand(1000)
Shellsort(R)
verifica_d_ordenado(R,1)

1001
Arreglo 1-ordenado OK.


## 3) Probar con una secuencia diferente de valores $d_i$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_i$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

Una secuencia que provoca una complejidad de tiempo de $O(n^{\frac{4}{3}})$ en el shellsort es la secuencia [N° A033622](https://oeis.org/A033622) en [la OEIS](https://oeis.org/wiki/welcome) (Online encyclopedia of Integer Sequences), la cual consiste en la siguiente formula analítica:

$$
 \begin{equation}
 S_k =
   \left\{\begin{array}{lr}
       2^{2(k-1)} + 3\cdot 2^{k-2} + 1, & k \geq 1 \\
       1, & k=0 
    \end{array}\right.
 \end{equation}
$$

Esta secuencia fue buscada en [el articulo de shellsort de Wikipedia](https://en.wikipedia.org/wiki/Shellsort)

In [185]:
def oeis_seq(k: int) -> int:
    return 2 ** (2*k) + 3 * 2 ** (k - 1) + 1 if k != 0 else 1

for k in range(20,-1,-1):
    print(oeis_seq(k))

1099513200641
274878693377
68719869953
17180065793
4295065601
1073790977
268460033
67121153
16783361
4197377
1050113
262913
65921
16577
4193
1073
281
77
23
8
1


In [186]:
def alt_Shellsort(a):
    seq_d = [oeis_seq(k) for k in range(len(a), -1, -1)]
    print(len(seq_d))
    for d in seq_d:
        d_ordena_insercion(a,d)

R_2 = np.random.rand(1000)
alt_Shellsort(R_2)
verifica_d_ordenado(R_2,1)

1001
Arreglo 1-ordenado OK.


## ¿Qué hay que entregar?

Usted debe entregar este mismo archivo, modificado de acuerdo a lo que se pide. Haga todos los cambios necesarios para explicar y documentar adecuadamente su código. Cite todas las fuentes de información utilizadas. **No olvide poner su nombre en el encabezamiento**.